// Auto-generated from the local Excel/TXT knowledge bases used by InnerTide.
// Keep this file deterministic and free of API keys.

export type DietKnowledgeItem = {
  id: string; phase: string; type: string; name: string; examples: string;
  temperature: string; sugar: string; caffeine: string; spicy: string; dairy: string;
  seafood: string; nuts: string; egg: string; soy: string; gluten: string; animal: string; halal: string;
  painRange: string; benefit: string;
};

export type ExerciseKnowledgeItem = {
  id: string; phase: string; type: string; name: string; painRange: string; flowRange: string;
  intensity: string; duration: string; location: string; equipment: string; inverted: string; hipOpen: string; water: string; benefit: string;
};

export type LifeKnowledgeItem = {
  id: string; phase: string; subType: string; type: string; name: string; painRange: string; method: string;
  duration: string; benefit: string; contraindications: string;
};

export type ReactionKnowledgeItem = {
  title: string; aliases: string[]; body: string;
};

export const DIET_KNOWLEDGE = [
  {
    "id": "1",
    "phase": "月经期",
    "type": "推荐",
    "name": "补铁餐",
    "examples": "红肉+菠菜+橙子",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "否",
    "painRange": "1-10",
    "benefit": "补铁，防疲劳"
  },
  {
    "id": "2",
    "phase": "月经期",
    "type": "推荐",
    "name": "含镁零食",
    "examples": "杏仁、南瓜籽、香蕉",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "放松子宫肌肉，缓解痛经"
  },
  {
    "id": "3",
    "phase": "月经期",
    "type": "推荐",
    "name": "Omega-3 食物",
    "examples": "深海鱼、鱼油",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "抗炎，效果接近布洛芬"
  },
  {
    "id": "4",
    "phase": "月经期",
    "type": "推荐",
    "name": "红糖姜茶",
    "examples": "红糖姜茶",
    "temperature": "温热",
    "sugar": "高",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "镇痛，暖宫"
  },
  {
    "id": "5",
    "phase": "月经期",
    "type": "推荐",
    "name": "桂圆红枣茶",
    "examples": "桂圆红枣茶",
    "temperature": "温热",
    "sugar": "高",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "补气血"
  },
  {
    "id": "6",
    "phase": "月经期",
    "type": "推荐",
    "name": "温热汤粥",
    "examples": "鸡汤、小米粥、银耳羹",
    "temperature": "温热",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "可能含",
    "animal": "含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "易消化，暖胃"
  },
  {
    "id": "7",
    "phase": "月经期",
    "type": "推荐",
    "name": "维 C 食物",
    "examples": "橙子、猕猴桃、草莓",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "提升非血红素铁吸收 2-3 倍"
  },
  {
    "id": "8",
    "phase": "月经期",
    "type": "推荐",
    "name": "易消化蛋白",
    "examples": "鸡蛋、豆腐、鱼、鸡肉",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "不含",
    "egg": "可能含",
    "soy": "可能含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "经期消化弱，蛋白源易吸收"
  },
  {
    "id": "9",
    "phase": "月经期",
    "type": "避免",
    "name": "冰饮料",
    "examples": "冰水、冰可乐、冰奶茶",
    "temperature": "冰",
    "sugar": "高",
    "caffeine": "可能含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "—",
    "painRange": "1-10",
    "benefit": "血管收缩，加重痛经"
  },
  {
    "id": "10",
    "phase": "月经期",
    "type": "避免",
    "name": "冰淇淋",
    "examples": "各类冰淇淋",
    "temperature": "冰",
    "sugar": "高",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "可能含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "—",
    "painRange": "1-10",
    "benefit": "血管收缩 + 含乳"
  },
  {
    "id": "11",
    "phase": "月经期",
    "type": "避免",
    "name": "生冷凉拌",
    "examples": "凉拌菜、冰沙拉",
    "temperature": "凉",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "加重宫寒"
  },
  {
    "id": "12",
    "phase": "月经期",
    "type": "避免",
    "name": "浓茶",
    "examples": "浓泡绿茶/红茶",
    "temperature": "—",
    "sugar": "无",
    "caffeine": "含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "鞣酸抑制铁吸收"
  },
  {
    "id": "13",
    "phase": "月经期",
    "type": "限量",
    "name": "咖啡",
    "examples": "美式、拿铁",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "1-10",
    "benefit": "加重焦虑、乳房胀痛"
  },
  {
    "id": "14",
    "phase": "月经期",
    "type": "避免",
    "name": "高盐食物",
    "examples": "腌制品、火锅、外卖",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "不含",
    "spicy": "可能辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "可能含",
    "animal": "可能含",
    "halal": "—",
    "painRange": "1-10",
    "benefit": "加重水钠潴留"
  },
  {
    "id": "15",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "高蛋白餐",
    "examples": "鸡胸肉、瘦牛肉、虾、蛋",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "不含",
    "egg": "可能含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "—",
    "benefit": "运动期肌肉合成（1.2-1.6g/kg/天）"
  },
  {
    "id": "16",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "复合碳水",
    "examples": "燕麦、糙米、全麦面包、红薯",
    "temperature": "温热",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "可能含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "胰岛素敏感，碳水易利用"
  },
  {
    "id": "17",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "运动后补给",
    "examples": "香蕉+蛋白粉",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "30 分钟内补充，恢复糖原+修复肌肉"
  },
  {
    "id": "18",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "锌+维D 食物",
    "examples": "牡蛎、牛肉、南瓜籽",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "可能含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "—",
    "benefit": "支持免疫和肌肉"
  },
  {
    "id": "19",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "膳食纤维",
    "examples": "蔬菜、水果、全谷物、豆类",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "可能含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "促进雌激素代谢"
  },
  {
    "id": "20",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "益生菌食物",
    "examples": "酸奶、发酵食品、泡菜",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "维持肠道菌群"
  },
  {
    "id": "21",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "足量饮水",
    "examples": "每日 1.5-2L",
    "temperature": "常温",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "支持新陈代谢"
  },
  {
    "id": "22",
    "phase": "排卵期",
    "type": "推荐",
    "name": "充分补水",
    "examples": "每日 2-2.5L",
    "temperature": "常温",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "高强度训练防脱水"
  },
  {
    "id": "23",
    "phase": "排卵期",
    "type": "推荐",
    "name": "电解质",
    "examples": "运动饮料、电解质片",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "预防肌肉痉挛"
  },
  {
    "id": "24",
    "phase": "排卵期",
    "type": "推荐",
    "name": "富镁食物",
    "examples": "杏仁、香蕉、牛油果、菠菜",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "预防高强度运动抽筋"
  },
  {
    "id": "25",
    "phase": "排卵期",
    "type": "推荐",
    "name": "抗氧化食物",
    "examples": "蓝莓、猕猴桃、绿茶、黑巧",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "减少运动自由基"
  },
  {
    "id": "26",
    "phase": "排卵期",
    "type": "推荐",
    "name": "高蛋白",
    "examples": "鸡胸肉、鱼、蛋",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "不含",
    "egg": "可能含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "—",
    "benefit": "肌肉合成代谢窗口"
  },
  {
    "id": "27",
    "phase": "排卵期",
    "type": "推荐",
    "name": "富锌食物",
    "examples": "牡蛎、牛肉、南瓜籽、芝麻",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "可能含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "含",
    "halal": "是",
    "painRange": "—",
    "benefit": "支持免疫和激素合成"
  },
  {
    "id": "28",
    "phase": "排卵期",
    "type": "推荐",
    "name": "健康脂肪",
    "examples": "橄榄油、牛油果、坚果、深海鱼",
    "temperature": "常温",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "支持雌激素合成"
  },
  {
    "id": "29",
    "phase": "黄体期",
    "type": "推荐",
    "name": "复合碳水",
    "examples": "燕麦、糙米、全麦、红薯、豆类",
    "temperature": "温热",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "可能含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "色氨酸转化血清素，稳情绪"
  },
  {
    "id": "30",
    "phase": "黄体期",
    "type": "推荐",
    "name": "少食多餐",
    "examples": "每 3-4 小时一次",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "—",
    "spicy": "—",
    "dairy": "—",
    "seafood": "—",
    "nuts": "—",
    "egg": "—",
    "soy": "—",
    "gluten": "—",
    "animal": "—",
    "halal": "—",
    "painRange": "—",
    "benefit": "维持血糖稳定"
  },
  {
    "id": "31",
    "phase": "黄体期",
    "type": "推荐",
    "name": "补钙食物",
    "examples": "低脂奶、豆腐、芝麻酱、沙丁鱼",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "可能含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "PMS 风险降低 30%"
  },
  {
    "id": "32",
    "phase": "黄体期",
    "type": "推荐",
    "name": "维B6 食物",
    "examples": "香蕉、鹰嘴豆、三文鱼、鸡胸肉",
    "temperature": "温热",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "合成血清素和多巴胺"
  },
  {
    "id": "33",
    "phase": "黄体期",
    "type": "推荐",
    "name": "补镁食物",
    "examples": "70% 黑巧、南瓜籽、杏仁、菠菜",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "可能含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "缓解水肿、乳房胀痛、失眠"
  },
  {
    "id": "34",
    "phase": "黄体期",
    "type": "推荐",
    "name": "Omega-3",
    "examples": "三文鱼、沙丁鱼、亚麻籽、核桃",
    "temperature": "温热",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "可能含",
    "nuts": "可能含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "抗炎，减轻 PMS"
  },
  {
    "id": "35",
    "phase": "黄体期",
    "type": "限量",
    "name": "咖啡因",
    "examples": "<200mg/天",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "加重 PMS 症状"
  },
  {
    "id": "36",
    "phase": "黄体期",
    "type": "避免",
    "name": "高盐食物",
    "examples": "腌制品、火锅",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "不含",
    "spicy": "可能辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "可能含",
    "animal": "可能含",
    "halal": "—",
    "painRange": "—",
    "benefit": "加重水钠潴留"
  },
  {
    "id": "37",
    "phase": "黄体期",
    "type": "推荐",
    "name": "富钾食物",
    "examples": "香蕉、土豆、菠菜、牛油果",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "排钠，减轻水肿"
  },
  {
    "id": "38",
    "phase": "黄体期",
    "type": "推荐",
    "name": "维E 食物",
    "examples": "坚果、种子、橄榄油、菠菜",
    "temperature": "常温",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "缓解乳房胀痛"
  },
  {
    "id": "39",
    "phase": "黄体期",
    "type": "推荐",
    "name": "健康零食备餐",
    "examples": "坚果、黑巧、水果",
    "temperature": "常温",
    "sugar": "中",
    "caffeine": "可能含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "避免暴食冲动"
  },
  {
    "id": "40",
    "phase": "全周期",
    "type": "推荐",
    "name": "充足钙摄入",
    "examples": "奶制品、豆腐、深绿叶菜",
    "temperature": "常温",
    "sugar": "—",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "防骨密度流失（1000-1200mg/天）"
  },
  {
    "id": "41",
    "phase": "全周期",
    "type": "推荐",
    "name": "维生素 D",
    "examples": "日晒 15-20 分钟或补剂",
    "temperature": "—",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "促进钙吸收"
  },
  {
    "id": "42",
    "phase": "全周期",
    "type": "推荐",
    "name": "充足膳食纤维",
    "examples": "25-30g/天",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "可能含",
    "gluten": "可能含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "促进肠道蠕动 + 雌激素代谢"
  },
  {
    "id": "43",
    "phase": "全周期",
    "type": "推荐",
    "name": "益生菌",
    "examples": "酸奶、发酵食品、泡菜",
    "temperature": "常温",
    "sugar": "低",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "可能含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "可能含",
    "halal": "是",
    "painRange": "—",
    "benefit": "维持肠道菌群"
  },
  {
    "id": "44",
    "phase": "全周期",
    "type": "推荐",
    "name": "充足饮水",
    "examples": "1.5-2L/天",
    "temperature": "常温",
    "sugar": "无",
    "caffeine": "不含",
    "spicy": "不辣",
    "dairy": "不含",
    "seafood": "不含",
    "nuts": "不含",
    "egg": "不含",
    "soy": "不含",
    "gluten": "不含",
    "animal": "不含",
    "halal": "是",
    "painRange": "—",
    "benefit": "支持新陈代谢"
  },
  {
    "id": "45",
    "phase": "全周期",
    "type": "推荐",
    "name": "规律进食",
    "examples": "固定时间，不暴饮暴食",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "—",
    "spicy": "—",
    "dairy": "—",
    "seafood": "—",
    "nuts": "—",
    "egg": "—",
    "soy": "—",
    "gluten": "—",
    "animal": "—",
    "halal": "—",
    "painRange": "—",
    "benefit": "维持肠道生物钟"
  },
  {
    "id": "46",
    "phase": "全周期",
    "type": "避免",
    "name": "过度节食",
    "examples": "热量 ≥ 基础代谢",
    "temperature": "—",
    "sugar": "—",
    "caffeine": "—",
    "spicy": "—",
    "dairy": "—",
    "seafood": "—",
    "nuts": "—",
    "egg": "—",
    "soy": "—",
    "gluten": "—",
    "animal": "—",
    "halal": "—",
    "painRange": "—",
    "benefit": "防骨密度下降 + 激素紊乱"
  }
] satisfies DietKnowledgeItem[];

export const EXERCISE_KNOWLEDGE = [
  {
    "id": "1",
    "phase": "月经期",
    "type": "推荐",
    "name": "散步",
    "painRange": "1-5",
    "flowRange": "少,中",
    "intensity": "低",
    "duration": "20-30 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "促进盆腔血液循环"
  },
  {
    "id": "2",
    "phase": "月经期",
    "type": "推荐",
    "name": "婴儿式瑜伽",
    "painRange": "1-6",
    "flowRange": "少,中,多",
    "intensity": "低",
    "duration": "5-10 分钟",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "放松骨盆，缓解腰背"
  },
  {
    "id": "3",
    "phase": "月经期",
    "type": "推荐",
    "name": "猫牛式瑜伽",
    "painRange": "1-5",
    "flowRange": "少,中",
    "intensity": "低",
    "duration": "5 分钟",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "放松脊柱"
  },
  {
    "id": "4",
    "phase": "月经期",
    "type": "推荐",
    "name": "仰卧束角式",
    "painRange": "1-6",
    "flowRange": "少,中",
    "intensity": "低",
    "duration": "5-10 分钟",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "否",
    "hipOpen": "是",
    "water": "否",
    "benefit": "缓解骨盆紧张"
  },
  {
    "id": "5",
    "phase": "月经期",
    "type": "推荐",
    "name": "轻柔拉伸",
    "painRange": "1-5",
    "flowRange": "少,中",
    "intensity": "低",
    "duration": "10-15 分钟",
    "location": "居家",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "拉伸下背、髋部、大腿内侧"
  },
  {
    "id": "6",
    "phase": "月经期",
    "type": "推荐",
    "name": "盆底肌放松",
    "painRange": "1-10",
    "flowRange": "少,中,多",
    "intensity": "极低",
    "duration": "5 分钟",
    "location": "居家",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "缓解子宫收缩"
  },
  {
    "id": "7",
    "phase": "月经期",
    "type": "避免",
    "name": "HIIT",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "—",
    "equipment": "—",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "经期能量低"
  },
  {
    "id": "8",
    "phase": "月经期",
    "type": "避免",
    "name": "游泳",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "—",
    "location": "泳池",
    "equipment": "—",
    "inverted": "否",
    "hipOpen": "否",
    "water": "是",
    "benefit": "宫颈口微开易感染"
  },
  {
    "id": "9",
    "phase": "月经期",
    "type": "避免",
    "name": "倒立瑜伽",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "—",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "是",
    "hipOpen": "否",
    "water": "否",
    "benefit": "影响经血排出"
  },
  {
    "id": "10",
    "phase": "月经期",
    "type": "避免",
    "name": "大重量力量训练",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "能量低不适合"
  },
  {
    "id": "11",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "力量训练（大重量）",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "45-60 分钟",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "深蹲硬拉卧推 70-85% 1RM"
  },
  {
    "id": "12",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "中长距离有氧",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "30-45 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "慢跑骑行 60-75% 最大心率"
  },
  {
    "id": "13",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "HIIT",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "20-30 分钟",
    "location": "居家",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "快跑1分+慢走2分 × 6-8 轮"
  },
  {
    "id": "14",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "渐进超负荷",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "每周加重量或次数"
  },
  {
    "id": "15",
    "phase": "卵泡期",
    "type": "推荐",
    "name": "尝试新运动",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "—",
    "location": "户外",
    "equipment": "视项目",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "攀岩舞蹈拳击，神经可塑性最佳"
  },
  {
    "id": "16",
    "phase": "排卵期",
    "type": "推荐",
    "name": "PR 挑战",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "60-90 分钟",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "神经肌肉协调最佳"
  },
  {
    "id": "17",
    "phase": "排卵期",
    "type": "推荐",
    "name": "HIIT",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "20-30 分钟",
    "location": "居家",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "心肺功能最佳"
  },
  {
    "id": "18",
    "phase": "排卵期",
    "type": "推荐",
    "name": "大重量力量",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "60 分钟",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "80-90% 1RM"
  },
  {
    "id": "19",
    "phase": "排卵期",
    "type": "推荐",
    "name": "耐力运动",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "45-90 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "脂肪氧化效率最佳"
  },
  {
    "id": "20",
    "phase": "排卵期",
    "type": "推荐",
    "name": "敏捷训练",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "30 分钟",
    "location": "户外",
    "equipment": "绳梯锥桶",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "韧带松弛注意保护膝盖"
  },
  {
    "id": "21",
    "phase": "排卵期",
    "type": "推荐",
    "name": "参加比赛",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "—",
    "equipment": "—",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "周期最佳"
  },
  {
    "id": "22",
    "phase": "排卵期",
    "type": "推荐",
    "name": "充分热身",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "低",
    "duration": "10-15 分钟",
    "location": "—",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "动态拉伸+慢跑+关节，防 ACL"
  },
  {
    "id": "23",
    "phase": "排卵期",
    "type": "推荐",
    "name": "膝关节稳定",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "—",
    "location": "健身房",
    "equipment": "弹力带",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "降低韧带受伤风险"
  },
  {
    "id": "24",
    "phase": "排卵期",
    "type": "避免",
    "name": "不热身高强度",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "—",
    "equipment": "—",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "ACL 受伤风险增加"
  },
  {
    "id": "25",
    "phase": "排卵期",
    "type": "避免",
    "name": "连续多日 HIIT",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "高",
    "duration": "—",
    "location": "—",
    "equipment": "—",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "可能过度训练"
  },
  {
    "id": "26",
    "phase": "黄体期早",
    "type": "推荐",
    "name": "中等有氧",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "30-40 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "60-70% 最大心率"
  },
  {
    "id": "27",
    "phase": "黄体期早",
    "type": "推荐",
    "name": "力量训练（降重）",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "45 分钟",
    "location": "健身房",
    "equipment": "杠铃哑铃",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "比卵泡期降 10-15%"
  },
  {
    "id": "28",
    "phase": "黄体期早",
    "type": "推荐",
    "name": "瑜伽普拉提",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "30-45 分钟",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "保持灵活性"
  },
  {
    "id": "29",
    "phase": "黄体期早",
    "type": "推荐",
    "name": "户外运动",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "30-60 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "阳光促维 D，改善情绪"
  },
  {
    "id": "30",
    "phase": "黄体期晚",
    "type": "推荐",
    "name": "散步",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "低",
    "duration": "20-30 分钟",
    "location": "户外",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "改善情绪，缓解焦虑"
  },
  {
    "id": "31",
    "phase": "黄体期晚",
    "type": "推荐",
    "name": "舒缓瑜伽",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "低",
    "duration": "30 分钟",
    "location": "居家",
    "equipment": "瑜伽垫",
    "inverted": "否",
    "hipOpen": "可能",
    "water": "否",
    "benefit": "修复性瑜伽、阴瑜伽"
  },
  {
    "id": "32",
    "phase": "黄体期晚",
    "type": "推荐",
    "name": "拉伸+泡沫轴",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "低",
    "duration": "15-20 分钟",
    "location": "居家",
    "equipment": "泡沫轴",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "重点髋部、下背部"
  },
  {
    "id": "33",
    "phase": "黄体期晚",
    "type": "推荐",
    "name": "呼吸冥想",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "极低",
    "duration": "5-10 分钟",
    "location": "居家",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "腹式呼吸，激活副交感"
  },
  {
    "id": "34",
    "phase": "黄体期晚",
    "type": "推荐",
    "name": "水中运动",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "低",
    "duration": "30 分钟",
    "location": "泳池",
    "equipment": "不需",
    "inverted": "否",
    "hipOpen": "否",
    "water": "是",
    "benefit": "水压缓解水肿"
  },
  {
    "id": "35",
    "phase": "全周期",
    "type": "推荐",
    "name": "负重运动",
    "painRange": "—",
    "flowRange": "—",
    "intensity": "中",
    "duration": "—",
    "location": "健身房",
    "equipment": "杠铃弹力带",
    "inverted": "否",
    "hipOpen": "否",
    "water": "否",
    "benefit": "刺激骨密度，防骨质疏松"
  }
] satisfies ExerciseKnowledgeItem[];

export const LIFE_KNOWLEDGE = [
  {
    "id": "1",
    "phase": "月经期",
    "subType": "疼痛管理",
    "type": "推荐",
    "name": "热敷下腹",
    "painRange": "1-10",
    "method": "热水袋/暖宝宝敷下腹",
    "duration": "15-20 分钟",
    "benefit": "缓解痛经，接近止痛药",
    "contraindications": "皮肤敏感注意温度"
  },
  {
    "id": "2",
    "phase": "月经期",
    "subType": "疼痛管理",
    "type": "推荐（必要时）",
    "name": "服用止痛药",
    "painRange": "6-10",
    "method": "布洛芬 400mg 或萘普生 500mg（饭后）",
    "duration": "—",
    "benefit": "抑制前列腺素",
    "contraindications": "胃溃疡/肝肾异常/孕妇"
  },
  {
    "id": "3",
    "phase": "月经期",
    "subType": "疼痛管理",
    "type": "推荐（可选）",
    "name": "TENS 电刺激",
    "painRange": "4-10",
    "method": "家用 TENS 设备",
    "duration": "—",
    "benefit": "阻断疼痛信号",
    "contraindications": "心脏起搏器使用者"
  },
  {
    "id": "4",
    "phase": "月经期",
    "subType": "生活",
    "type": "推荐",
    "name": "温水泡脚",
    "painRange": "1-10",
    "method": "40°C 水温，可加姜片",
    "duration": "15 分钟",
    "benefit": "促进下肢循环",
    "contraindications": "—"
  },
  {
    "id": "5",
    "phase": "月经期",
    "subType": "生活",
    "type": "推荐",
    "name": "穿宽松衣物",
    "painRange": "1-10",
    "method": "避免紧身衣压迫腹部",
    "duration": "全天",
    "benefit": "减轻腹胀",
    "contraindications": "—"
  },
  {
    "id": "6",
    "phase": "月经期",
    "subType": "生活",
    "type": "推荐",
    "name": "允许自己休息",
    "painRange": "1-10",
    "method": "减少社交和工作强度",
    "duration": "—",
    "benefit": "顺应身体蛰伏信号",
    "contraindications": "—"
  },
  {
    "id": "7",
    "phase": "月经期",
    "subType": "生活",
    "type": "推荐",
    "name": "记录感受",
    "painRange": "1-10",
    "method": "小岛日记记录身体和情绪",
    "duration": "1-2 分钟",
    "benefit": "发现周期规律",
    "contraindications": "—"
  },
  {
    "id": "8",
    "phase": "月经期",
    "subType": "睡眠",
    "type": "推荐",
    "name": "提前 30 分钟入睡",
    "painRange": "1-10",
    "method": "比平时早睡，安静黑暗",
    "duration": "—",
    "benefit": "经期需更多恢复",
    "contraindications": "—"
  },
  {
    "id": "9",
    "phase": "月经期",
    "subType": "睡眠",
    "type": "推荐（可选）",
    "name": "重力毯",
    "painRange": "1-10",
    "method": "体重 7-12% 重量",
    "duration": "整夜",
    "benefit": "促进褪黑素",
    "contraindications": "呼吸系统疾病"
  },
  {
    "id": "10",
    "phase": "月经期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "加强保湿",
    "painRange": "1-10",
    "method": "透明质酸/神经酰胺保湿品",
    "duration": "早晚",
    "benefit": "修复皮肤屏障",
    "contraindications": "—"
  },
  {
    "id": "11",
    "phase": "月经期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "防晒",
    "painRange": "1-10",
    "method": "SPF30+ 防晒霜",
    "duration": "出门前",
    "benefit": "经期紫外线修复弱",
    "contraindications": "—"
  },
  {
    "id": "12",
    "phase": "月经期",
    "subType": "生活",
    "type": "避免",
    "name": "熬夜",
    "painRange": "1-10",
    "method": "—",
    "duration": "—",
    "benefit": "经期需更多恢复",
    "contraindications": "—"
  },
  {
    "id": "13",
    "phase": "月经期",
    "subType": "睡眠",
    "type": "避免",
    "name": "睡前刷手机",
    "painRange": "1-10",
    "method": "—",
    "duration": "—",
    "benefit": "蓝光抑制褪黑素",
    "contraindications": "—"
  },
  {
    "id": "14",
    "phase": "月经期",
    "subType": "皮肤",
    "type": "避免",
    "name": "深层清洁/去角质",
    "painRange": "1-10",
    "method": "—",
    "duration": "—",
    "benefit": "皮肤敏感易刺激",
    "contraindications": "—"
  },
  {
    "id": "15",
    "phase": "卵泡期",
    "subType": "生活",
    "type": "推荐",
    "name": "设定健身目标",
    "painRange": "—",
    "method": "利用精力旺盛期开始新计划",
    "duration": "—",
    "benefit": "顺应能量上升期建立习惯",
    "contraindications": "—"
  },
  {
    "id": "16",
    "phase": "卵泡期",
    "subType": "睡眠",
    "type": "推荐",
    "name": "7-9 小时睡眠",
    "painRange": "—",
    "method": "固定作息，远离屏幕",
    "duration": "整夜",
    "benefit": "肌肉修复和激素平衡",
    "contraindications": "—"
  },
  {
    "id": "17",
    "phase": "卵泡期",
    "subType": "生活",
    "type": "推荐",
    "name": "记录训练数据",
    "painRange": "—",
    "method": "小岛日记记录重量、组数",
    "duration": "训练后",
    "benefit": "追踪进步",
    "contraindications": "—"
  },
  {
    "id": "18",
    "phase": "卵泡期",
    "subType": "生活",
    "type": "推荐",
    "name": "安排重要工作",
    "painRange": "—",
    "method": "创造力和专注任务排本周",
    "duration": "—",
    "benefit": "认知功能最佳",
    "contraindications": "—"
  },
  {
    "id": "19",
    "phase": "卵泡期",
    "subType": "生活",
    "type": "推荐",
    "name": "社交活动",
    "painRange": "—",
    "method": "聚会、约会、团队合作",
    "duration": "—",
    "benefit": "情绪稳定",
    "contraindications": "—"
  },
  {
    "id": "20",
    "phase": "卵泡期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "尝试新护肤品",
    "painRange": "—",
    "method": "引入新的精华或面膜",
    "duration": "—",
    "benefit": "皮肤稳定不易过敏",
    "contraindications": "敏感肌先小范围试用"
  },
  {
    "id": "21",
    "phase": "卵泡期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "深层清洁",
    "painRange": "—",
    "method": "每周 1-2 次去角质",
    "duration": "—",
    "benefit": "皮肤代谢旺盛",
    "contraindications": "—"
  },
  {
    "id": "22",
    "phase": "卵泡期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "抗氧化护理",
    "painRange": "—",
    "method": "维 C、烟酰胺产品",
    "duration": "早晚",
    "benefit": "雌激素促胶原合成",
    "contraindications": "—"
  },
  {
    "id": "23",
    "phase": "排卵期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "强化防晒",
    "painRange": "—",
    "method": "SPF50+，每 2 小时补涂",
    "duration": "出门时",
    "benefit": "紫外线敏感",
    "contraindications": "—"
  },
  {
    "id": "24",
    "phase": "排卵期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "控油护理",
    "painRange": "—",
    "method": "水杨酸或烟酰胺",
    "duration": "早晚",
    "benefit": "皮脂分泌增加",
    "contraindications": "敏感肌注意浓度"
  },
  {
    "id": "25",
    "phase": "排卵期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "运动后及时清洁",
    "painRange": "—",
    "method": "出汗后第一时间洁面",
    "duration": "—",
    "benefit": "防毛孔堵塞",
    "contraindications": "—"
  },
  {
    "id": "26",
    "phase": "黄体期",
    "subType": "睡眠",
    "type": "推荐",
    "name": "降低卧室温度",
    "painRange": "—",
    "method": "空调降 1-2°C，透气床品",
    "duration": "整夜",
    "benefit": "孕激素升温，凉爽助眠",
    "contraindications": "—"
  },
  {
    "id": "27",
    "phase": "黄体期",
    "subType": "睡眠",
    "type": "推荐",
    "name": "睡前温水浴",
    "painRange": "—",
    "method": "睡前 1-2 小时",
    "duration": "20-30 分钟",
    "benefit": "体温先升后降助入睡",
    "contraindications": "—"
  },
  {
    "id": "28",
    "phase": "黄体期",
    "subType": "睡眠",
    "type": "避免",
    "name": "睡前大量进食",
    "painRange": "—",
    "method": "睡前 2-3 小时不进食",
    "duration": "—",
    "benefit": "影响睡眠深度",
    "contraindications": "—"
  },
  {
    "id": "29",
    "phase": "黄体期",
    "subType": "睡眠",
    "type": "推荐（可选）",
    "name": "重力毯",
    "painRange": "—",
    "method": "体重 7-12% 重量",
    "duration": "整夜",
    "benefit": "促褪黑素",
    "contraindications": "呼吸系统疾病"
  },
  {
    "id": "30",
    "phase": "黄体期",
    "subType": "睡眠",
    "type": "推荐（可选）",
    "name": "睡前温牛奶",
    "painRange": "—",
    "method": "一杯温牛奶",
    "duration": "睡前",
    "benefit": "色氨酸助眠",
    "contraindications": "乳糖不耐"
  },
  {
    "id": "31",
    "phase": "黄体期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "控油清洁",
    "painRange": "—",
    "method": "水杨酸洁面产品",
    "duration": "早晚",
    "benefit": "孕激素刺激皮脂，易长痘",
    "contraindications": "敏感肌注意浓度"
  },
  {
    "id": "32",
    "phase": "黄体期",
    "subType": "皮肤",
    "type": "避免",
    "name": "厚重护肤品",
    "painRange": "—",
    "method": "—",
    "duration": "—",
    "benefit": "毛孔易堵塞",
    "contraindications": "—"
  },
  {
    "id": "33",
    "phase": "黄体期",
    "subType": "皮肤",
    "type": "避免",
    "name": "挤痘痘",
    "painRange": "—",
    "method": "用痘痘贴或点涂",
    "duration": "—",
    "benefit": "挤压加重炎症+留疤",
    "contraindications": "—"
  },
  {
    "id": "34",
    "phase": "黄体期",
    "subType": "皮肤",
    "type": "推荐",
    "name": "加强防晒",
    "painRange": "—",
    "method": "SPF30+ 防色沉",
    "duration": "出门前",
    "benefit": "炎症后易色沉",
    "contraindications": "—"
  },
  {
    "id": "35",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "穿宽松衣服",
    "painRange": "—",
    "method": "避免紧身衣压迫腹部",
    "duration": "全天",
    "benefit": "减轻腹胀",
    "contraindications": "—"
  },
  {
    "id": "36",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "记录情绪变化",
    "painRange": "—",
    "method": "小岛日记记录心情",
    "duration": "1-2 分钟",
    "benefit": "识别 PMS 模式",
    "contraindications": "—"
  },
  {
    "id": "37",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "允许自己慢下来",
    "painRange": "—",
    "method": "减少社交和工作强度",
    "duration": "—",
    "benefit": "顺应内省能量",
    "contraindications": "—"
  },
  {
    "id": "38",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "安排轻松社交",
    "painRange": "—",
    "method": "与亲密朋友小聚",
    "duration": "—",
    "benefit": "情绪波动期更舒适",
    "contraindications": "—"
  },
  {
    "id": "39",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "健康零食备餐",
    "painRange": "—",
    "method": "坚果、黑巧、水果随手可及",
    "duration": "—",
    "benefit": "避免冲动暴食",
    "contraindications": "坚果过敏"
  },
  {
    "id": "40",
    "phase": "黄体期",
    "subType": "生活",
    "type": "推荐",
    "name": "轻柔自我按摩",
    "painRange": "—",
    "method": "精油按摩腹腰腿",
    "duration": "10-15 分钟",
    "benefit": "促进循环",
    "contraindications": "精油过敏"
  },
  {
    "id": "41",
    "phase": "全周期",
    "subType": "情绪",
    "type": "推荐",
    "name": "每天记录情绪",
    "painRange": "—",
    "method": "小岛日记写下心情",
    "duration": "1-2 分钟",
    "benefit": "发现情绪周期规律",
    "contraindications": "—"
  },
  {
    "id": "42",
    "phase": "全周期",
    "subType": "情绪",
    "type": "推荐",
    "name": "正念冥想",
    "painRange": "—",
    "method": "每日冥想或专注呼吸",
    "duration": "5-10 分钟",
    "benefit": "降低皮质醇",
    "contraindications": "—"
  },
  {
    "id": "43",
    "phase": "全周期",
    "subType": "情绪",
    "type": "推荐",
    "name": "保持社交联系",
    "painRange": "—",
    "method": "与朋友家人保持联系",
    "duration": "—",
    "benefit": "社会支持缓冲压力",
    "contraindications": "—"
  },
  {
    "id": "44",
    "phase": "全周期",
    "subType": "情绪",
    "type": "推荐",
    "name": "接触自然",
    "painRange": "—",
    "method": "每周至少 2 小时户外",
    "duration": "2+ 小时/周",
    "benefit": "自然光调节生物钟",
    "contraindications": "—"
  },
  {
    "id": "45",
    "phase": "全周期",
    "subType": "认知",
    "type": "推荐",
    "name": "卵泡期安排重要任务",
    "painRange": "—",
    "method": "创造力任务排在卵泡期",
    "duration": "—",
    "benefit": "雌激素高，认知最佳",
    "contraindications": "—"
  },
  {
    "id": "46",
    "phase": "全周期",
    "subType": "认知",
    "type": "推荐",
    "name": "黄体期减少多任务",
    "painRange": "—",
    "method": "一次只做一件事",
    "duration": "—",
    "benefit": "孕激素镇静影响多任务",
    "contraindications": "—"
  },
  {
    "id": "47",
    "phase": "全周期",
    "subType": "睡眠",
    "type": "推荐",
    "name": "7-9 小时睡眠",
    "painRange": "—",
    "method": "每晚 7-9 小时",
    "duration": "整夜",
    "benefit": "巩固记忆 + 支持认知",
    "contraindications": "—"
  }
] satisfies LifeKnowledgeItem[];

export const REACTION_KNOWLEDGE = [
  {
    "title": "😥 经前烦躁 / 想哭 / 内耗",
    "aliases": [
      "经前烦躁",
      "想哭",
      "内耗"
    ],
    "body": "- 正常机制解析：这与月经周期后半段（黄体期）的激素波动直接相关。\n- 排卵后雌激素和孕激素水平快速下降，这种激素撤退会影响大脑中负责情绪调节的神经递质，特别是 血清素（5-羟色胺）。血清素是保持情绪稳定、愉悦的核心物质，激素波动会导致其功能紊乱或分泌不足。\n- 近90%的女性会经历至少一种经前症状。其中约20%-30%的女性症状较为明显，符合经前期综合征的标准；2%-5%的女性症状非常严重，对生活造成显著影响，这可能属于经前焦虑障碍（PMDD） 。\n- “自我调节”之外更科学的方案：\n- 记录与观察：建议连续记录2-3个月经周期的每日症状，这是自我了解的基础。\n- 非药物缓解：\n        1.  睡眠充足：优质睡眠对稳定情绪至关重要。\n        2.  降低消耗：这几天减少复杂、高压的任务，允许自己节奏放慢。\n        3.  规律运动：温和的规律运动有助改善经前情绪。\n        4.  补充剂支持：一些研究表明，每日补充钙（400mg，每日三次）和镁（250mg，每日1-2次） 可能对部分女性有帮助。\n- 就医指引：如果情绪问题严重到影响正常工作、学习或人际关系，并持续出现强烈的悲伤、绝望感，甚至自杀念头，请务必就医。医生会根据情况做出诊断，并提供认知行为疗法、药物治疗等专业方案。"
  },
  {
    "title": "🍫 经前暴食 / 特别想吃甜食",
    "aliases": [
      "经前暴食",
      "特别想吃甜食"
    ],
    "body": "- 正常机制解析：这并非意志力薄弱，而是身体的生理需求信号。\n- 黄体期，孕激素升高、雌激素下降会影响体内的饥饿素和瘦素平衡，让大脑更容易产生饥饿感。同时，经前血清素水平的下降，会让大脑对能快速提升血清素的碳水化合物产生强烈渴望，以获得短暂的平静和愉悦。\n- “自我调节”之外更科学的方案：\n- 战略性满足：黄体期每日可适当增加100-200大卡的健康热量预算。\n- 智慧选择，平稳血糖：优先选择复合碳水化合物（如燕麦、红薯、糙米）和优质蛋白，它们能更平稳地提供饱腹感和能量。当想吃甜食时，一小块70%以上可可含量的黑巧克力或一杯无糖酸奶配浆果是很好的选择。\n- 优化生活方式：保证7-8小时的充足睡眠，睡眠不足会干扰饥饿素分泌，增加对高热量食物的渴望。可提前准备健康零食（如原味坚果、蓝莓）应对不时之需。"
  },
  {
    "title": "😣 痛经 / 小腹坠痛 / 腰酸",
    "aliases": [
      "痛经",
      "小腹坠痛",
      "腰酸"
    ],
    "body": "- 正常机制解析：这是身体为了排出内膜而进行的正常生理活动。\n- 月经来潮时，子宫内膜会释放一种叫“前列腺素”的化学物质，它能刺激子宫肌肉剧烈收缩，帮助排出经血。这种收缩可能压迫周围血管，导致子宫局部缺血、缺氧，从而引发疼痛。如果前列腺素分泌过多，收缩过于强烈或不协调，就会导致严重的疼痛。\n- “自我调节”之外更科学的方案：\n- 首选药物：非甾体抗炎药（NSAIDs）（如布洛芬、萘普生）是国际公认的一线用药。它通过抑制前列腺素的合成，从根源上缓解子宫痉挛性收缩。最佳服用时机是在预计痛经开始前1-2天或疼痛初期，效果最好。\n- 有效非药物措施：下腹部热敷可以放松肌肉、促进局部血液循环，是有效的辅助止痛方法。\n- 就医指引：如果痛经痛到无法正常生活、逐年加重、常规止痛药无效，或伴有发烧、异常分泌物，需要及时就医，排除子宫内膜异位症、子宫腺肌症等可能的病因。"
  },
  {
    "title": "💤 疲惫 / 注意力下降 / 不想工作学习",
    "aliases": [
      "疲惫",
      "注意力下降",
      "不想工作学习"
    ],
    "body": "- 正常机制解析：这是大脑的“节能模式”，并非你变懒了。\n- 黄体期升高的孕激素及其代谢产物（如别孕烯醇酮）对大脑有天然的镇静、安神作用，这会直接导致嗜睡和疲劳感。同时，雌激素水平的下降也可能影响记忆力、注意力和认知功能。\n- 睡眠悖论：尽管孕激素有镇静作用，但黄体后期的激素撤退却可能干扰睡眠调节，导致入睡困难、睡眠浅、易醒等问题，进一步加剧白天的疲劳。\n- “自我调节”之外更科学的方案：\n- 学会放松，接纳低能量状态：告诉自己，这是正常的生理反应，坦然接纳。\n- 任务管理：将复杂任务拆解为小目标，优先处理低认知负担的常规工作。可以尝试番茄工作法（工作25分钟，休息5分钟）。\n- 保证休息：允许自己在午休或傍晚小睡片刻，晚上尽量早睡。"
  },
  {
    "title": "🌊 水肿 / 胀气 / 胃不舒服 / 腹泻",
    "aliases": [
      "水肿",
      "胀气",
      "胃不舒服",
      "腹泻"
    ],
    "body": "- 正常机制解析：这也是激素波动的直接体现。\n- 水肿与腹胀：经前高水平的雌激素会促使身体保留更多钠离子，导致水钠潴留，水分滞留在组织间隙，引起体重增加（可多2公斤）、手脚和眼睑浮肿。\n- 腹泻与胃不适：主要原因同样是前列腺素。它在促进子宫收缩的同时，也会作用于肠道平滑肌，使其蠕动加快，肠道通过时间缩短，从而导致腹泻。\n- “自我调节”之外更科学的方案：\n- 管理水肿与腹胀：\n        1.  控盐：将每日食盐控制在5克以内，少吃加工食品和咸菜。\n        2.  补钾：多吃香蕉、菠菜、土豆等富含钾的食物，帮助平衡电解质，排出多余钠。\n        3.  利水食物：适当吃些红豆、薏米等。\n- 管理腹泻与胃不适：\n        1.  温热饮食：腹泻期间，喝温水或姜茶，避免咖啡、冰饮和辛辣食物。\n        2.  避免刺激：经前和经期，注意观察哪些食物会加重肠胃不适，并尽量避免。"
  }
] satisfies ReactionKnowledgeItem[];
